#!/system/bin/sh
# Seedvault Backup Magisk module - uninstall hook
# SPDX-License-Identifier: Apache-2.0
#
# Magisk runs this at post-fs-data when the module is removed, i.e. very early
# in boot when bmgr / the backup service are NOT available yet. We therefore
# cannot switch the transport here directly. Instead we drop a one-shot script
# into /data/adb/service.d that runs later in THIS same boot (late_start),
# waits for boot to complete, restores the previous (Google) backup transport
# and then deletes itself.

STATE_DIR="/data/adb/seedvault-magisk"
PREV_FILE="$STATE_DIR/previous_transport"
GOOGLE_TRANSPORT="com.google.android.gms/.backup.BackupTransportService"
RESTORE="/data/adb/service.d/seedvault_restore_transport.sh"

PREV="$(cat "$PREV_FILE" 2>/dev/null)"
[ -z "$PREV" ] && PREV="$GOOGLE_TRANSPORT"

mkdir -p /data/adb/service.d

cat > "$RESTORE" <<EOF
#!/system/bin/sh
# One-shot: restore the pre-Seedvault backup transport, then remove self.
# Generated by the Seedvault Backup Magisk module on uninstall.
(
  i=0
  while [ "\$(getprop sys.boot_completed)" != "1" ]; do
    sleep 3
    i=\$((i + 1))
    [ "\$i" -gt 200 ] && break
  done
  sleep 15
  bmgr enable true >/dev/null 2>&1
  bmgr transport "$PREV" >/dev/null 2>&1
  log -t SeedvaultModule "restored backup transport to: $PREV"
  rm -rf "$STATE_DIR"
  rm -f "$RESTORE"
) &
EOF

chmod 0755 "$RESTORE"
